name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Extract branch name
        shell: bash
        run: ORIGIN_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
      - name: Extract PR type
        shell: bash
        run: PR_TYPE=$(echo "$ORIGIN_BRANCH" | cut -d '/' -f 1)
      - name: Show PR type
        shell: bash
        run: echo $PR_TYPE
